spring:
    application:
        name: config-server
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    fail-on-error: true
                    search-locations: file:///D:/spam/config

server:
    port: 8280